name:                deadtext
version:             0.1.0.0
github:              "sethroot/deadtext"
license:             MIT
author:              "Seth Root"
maintainer:          "sethroot.io@gmail.com"
copyright:           "(c) 2021 Seth Root"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sethroot/deadtext#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- containers
- split
- mmorph
- aeson
- aeson-pretty
- bytestring
- lens
- safe
- errors
- pretty-simple

library:
  source-dirs: src

executables:
  deadtext-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deadtext

tests:
  deadtext-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deadtext
